'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const F=require('../web/query-feedback.js'),E=require('../scripts/eval_user_queries.cjs'),{createScorer}=require('../web/scorer.js');
const map=require('../maps/quest-coder/map.json'),p=E.provenance(map),copy=x=>JSON.parse(JSON.stringify(x));
function setup(fail){const data=new Map(),calls=[];let time='2026-10-08T06:00:00.000Z';const storage={getItem(k){calls.push(['get',k]);if(fail==='denied')throw Error('denied');return data.get(k)||null;},setItem(k,v){calls.push(['set',k]);if(fail)throw Error(fail);data.set(k,v);}};const s=F.createStore(map,storage,p,()=>time);return {s,data,calls,setTime:t=>time=t};}
function capture(s,q='Python judge',overlay=[]){return s.capture(q,createScorer(map,overlay).score(q),overlay,'generated-fixture');}
const truth=(operation='LOCATE',target='runner-service')=>({operation,target,from:null,to:null,route:null});
function labeled(){const {s}=setup();s.enable('generated-fixture');const id=capture(s);s.label(id,'Correct',truth(),'development');return s;}
test('off default does not read or write storage, including Ask and empty clear',()=>{const {s,calls}=setup();capture(s);s.clear();assert.equal(s.state().enabled,false);assert.deepEqual(calls,[]);assert.equal(s.state().records.length,0);});
test('explicit consent captures compact original/source/overlay, no probability arrays',()=>{const {s,calls}=setup();s.enable('generated-fixture');capture(s,'judge stop',[{alias:'judge stop',nodeId:'runner-service'}]);const r=s.state().records[0];assert.equal(r.origin,'generated-fixture');assert.equal(r.expected,null);assert.equal(r.snapshot.commit,map.meta.snapshot_commit);assert.deepEqual(r.snapshot.source,map.meta);assert.equal(r.snapshot.scorerSha256,p.scorerSha256);assert.equal(r.answer.targets.locate_target.choice,'runner-service');assert.ok(!s.serialize().includes('probabilities'));assert.equal(calls.filter(c=>c[0]==='set').length,1);});
test('disable stops capture; reloaded page requires consent again before reads',()=>{const {s,data}=setup();s.enable('user');capture(s);s.disable();capture(s);assert.equal(s.state().records.length,1);const s2=F.createStore(map,{getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},p);assert.equal(s2.state().records.length,0);assert.equal(s2.state().enabled,false);s2.enable('user');assert.equal(s2.state().records.length,1);});
test('Wrong leaves replacement unknown and Unclear never NOT_SURE truth',()=>{const {s}=setup();s.enable('user');const id=capture(s);s.label(id,'Wrong',null,'development');assert.equal(s.state().records[0].expected,null);s.label(id,'Unclear',null,'development');assert.throws(()=>s.label(id,'Unclear',truth('NOT_SURE',null),'development'),/Unclear/);const e=E.evaluate(map,s.serialize());assert.equal(e.eligible,0);assert.equal(e.counts.Unclear,1);assert.match(e.message,/No labeled user cases yet/);});
test('held-out freezes before labeling; development split cannot silently move',()=>{const {s}=setup();s.enable('user');const id=capture(s);s.label(id,'Correct',truth(),'heldout');const r=s.state().records[0];assert.ok(Date.parse(r.splitFrozenAt)<=Date.parse(r.labeledAt));assert.throws(()=>s.label(id,'Wrong',truth(),'development'),/frozen/);const s2=labeled();s2.label(s2.state().records[0].id,'Correct',truth(),'heldout');assert.equal(s2.state().records[0].split,'development');});
test('PATH independent expectations, invalid or mixed endpoints fail atomically',()=>{const {s}=setup();s.enable('user');const id=capture(s,'path from runner-service to database');const before=s.serialize();assert.throws(()=>s.label(id,'Wrong',{operation:'PATH',target:null,from:'invented',to:'persistence',route:'none'},'development'),/Unknown/);assert.equal(s.serialize(),before);assert.throws(()=>s.label(id,'Wrong',{operation:'PATH',target:null,from:'runner-service',to:'runner/quest_runner.py',route:'none'},'development'),/mixed/);s.label(id,'Wrong',{operation:'PATH',target:null,from:'runner-service',to:'persistence',route:'none'},'development');assert.equal(s.state().records[0].expected.to,'persistence');});
test('remove and clear do not alter alias namespace; exports roundtrip',()=>{const {s,data}=setup();data.set('dag-gps:aliases:v1:fixture','keep');s.enable('user');const id=capture(s);capture(s,'persistence');s.remove(id);assert.equal(F.parse(s.serialize(),map.meta.repo).records.length,1);s.clear();assert.equal(F.parse(s.serialize(),map.meta.repo).records.length,0);assert.equal(data.get('dag-gps:aliases:v1:fixture'),'keep');});
test('preview/commit import explicitly consented, stale snapshots quarantined',()=>{const s=labeled(),{s:dest}=setup();const preview=dest.preview(s.serialize());assert.equal(dest.state().records.length,0);assert.throws(()=>dest.commit(preview),/consent/);dest.enable('user');dest.commit(preview);assert.equal(dest.state().records.length,1);const d=JSON.parse(s.serialize());d.records[0].snapshot.commit='a'.repeat(40);d.records[0].snapshot.source.snapshot_commit='a'.repeat(40);const stale=dest.preview(d);assert.equal(stale.ineligible,1);dest.commit(stale);assert.equal(E.evaluate(map,d).ineligible.length,1);assert.throws(()=>dest.label(d.records[0].id,'Correct',truth(),'development'),/Stale/);});
test('malformed/version/oversize/unknown IDs/duplicate repo imports atomic',()=>{const s=labeled(),before=s.serialize();const base=JSON.parse(before),variants=['{',' '.repeat(F.MAX_BYTES+1),{...base,version:2},{...base,repo:'foreign/repo'},{...base,records:[base.records[0],base.records[0]]}];let d=copy(base);d.records[0].expected.target='unknown-id';variants.push(d);d=copy(base);d.records[0].answer.targets.locate_target.top3.push('unknown-id');variants.push(d);d=copy(base);d.records[0].splitFrozenAt='2027-10-08T00:00:00Z';variants.push(d);for(const bad of variants){assert.throws(()=>s.preview(bad));assert.equal(s.serialize(),before);}});
test('200 record and 90-day retention limits; oversize questions not recorded',()=>{const {s,setTime}=setup();s.enable('user');const answer=createScorer(map).score('persistence');for(let i=0;i<205;i++)s.capture('database '+i,answer,[],'generated-fixture');assert.equal(s.state().records.length,200);assert.ok(Buffer.byteLength(s.serialize())<=F.MAX_BYTES);setTime('2027-01-09T00:00:00Z');capture(s);assert.equal(s.state().records.length,1);assert.equal(s.capture('x'.repeat(2001),answer,[],'user'),null);});
for(const fail of ['denied','quota'])test('storage '+fail+' remains usable/unsaved/exportable',()=>{const {s}=setup(fail);s.enable('user');capture(s);assert.match(s.state().status,/Unsaved/);assert.equal(s.state().records.length,1);assert.equal(F.parse(s.serialize(),map.meta.repo).records.length,1);});
test('no labeled user cases reports absence, never invented accuracy',()=>{const {s}=setup();assert.deepEqual(E.evaluate(map,s.serialize()).groups,{});const e=E.evaluate(map,labeled().serialize());assert.equal(e.userLabeledCases,0);assert.equal(e.groups['generated-fixture/development'].original.operationTop1.count,1);assert.match(e.message,/No labeled user cases yet/);});
test('evaluator detects stale graph/scorer/unknown candidate/tampered original as ineligible',()=>{const d=JSON.parse(labeled().serialize());for(const mutate of [r=>r.snapshot.mapSha256='b'.repeat(64),r=>r.snapshot.scorerSha256='b'.repeat(64),r=>r.answer.targets.locate_target.choice='unknown',r=>r.answer.reason='tampered']){const c=copy(d);mutate(c.records[0]);assert.equal(E.evaluate(map,c).ineligible.length,1);assert.equal(E.evaluate(map,c).eligible,0);}});
test('alias-off/on separate; accepted wrong and unnecessary abstention retain misses',()=>{const {s}=setup();s.enable('user');const id=capture(s,'Python judge station',[{alias:'Python judge station',nodeId:'runner-service'}]);s.label(id,'Correct',truth(),'development');const bad=capture(s,'Python judge');s.label(bad,'Wrong',truth('LOCATE','persistence'),'development');const e=E.evaluate(map,s.serialize()).groups['generated-fixture/development'];assert.equal(e['alias-on'].acceptedWrongTargetsOrOperation.count,1);assert.equal(e['alias-off'].unnecessaryAbstention.count,1);assert.equal(e['alias-on'].latency.samples,40);});
test('route truth independent BFS excludes realtime, contradiction ineligible',()=>{const {s}=setup();s.enable('user');const id=capture(s,'path from runner-service to database');const exists=E.bfs(map,'runner-service','persistence');s.label(id,'Correct',{operation:'PATH',target:null,from:'runner-service',to:'persistence',route:exists?'found':'none'},'heldout');let d=JSON.parse(s.serialize());assert.equal(E.evaluate(map,d).eligible,1);d.records[0].expected.route=exists?'none':'found';assert.match(E.evaluate(map,d).ineligible[0].reason,/independent BFS/);const mini={nodes:[{id:'a'},{id:'b'}],edges:[{from:'a',to:'b',type:'realtime'}],file_edges:[]};assert.equal(E.bfs(mini,'a','b'),false);});

test('existing heldout and split provenance cannot be replaced by import',()=>{const {s}=setup();s.enable('user');const id=capture(s);s.label(id,'Correct',truth(),'heldout');const before=s.serialize(),d=JSON.parse(before);d.records[0].expected.target='auth';assert.throws(()=>s.preview(d),/Frozen/);assert.equal(s.serialize(),before);const dev=labeled(),dd=JSON.parse(dev.serialize());dd.records[0].split='heldout';assert.throws(()=>dev.preview(dd),/Frozen/);});
test('byte budget evicts oldest; exported UTF-8 JSON remains within import bound',()=>{const big=copy(map);big.meta.fixturePadding='λ'.repeat(10000);const {data,calls}=setup();const s=F.createStore(big,{getItem:k=>data.get(k)||null,setItem:(k,v)=>{calls.push(k);data.set(k,v);}},p,()=> '2026-10-08T06:00:00Z');s.enable('generated-fixture');const a=createScorer(big).score('Python judge');for(let i=0;i<110;i++)s.capture('budget fixture '+i,a,[],'generated-fixture');assert.ok(s.state().records.length<110);assert.ok(Buffer.byteLength(s.serialize(),'utf8')<=F.MAX_BYTES);assert.equal(F.parse(s.serialize(),map.meta.repo).records.at(-1).question,'budget fixture 109');});
test('heldout cannot be retroactively assigned after first label',()=>{const {s}=setup();s.enable('user');const id=capture(s);s.label(id,'Correct',truth(),'unassigned');assert.throws(()=>s.label(id,'Correct',truth(),'heldout'),/before first label/);});
test('preview rejects concurrent capture instead of silently dropping new history',()=>{const s=labeled(),preview=s.preview(s.serialize());capture(s);const before=s.serialize();assert.throws(()=>s.commit(preview),/changed after preview/);assert.equal(s.serialize(),before);});
