#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_DIR||'/Users/aibert/projects/quest-coder-assist/node_modules/playwright');
const axe=process.env.AXE_CORE_PATH||'/Users/aibert/projects/quest-coder-assist/node_modules/axe-core/axe.min.js';
(async()=>{const browser=await chromium.launch(),report={timestamp:new Date().toISOString(),axe:fs.existsSync(axe)?axe:null,states:[],errors:[],requests:[],screenshots:[]};try{for(const file of ['dist/quest-refresh/index.html','dist/dag-gps/index.html','dist/onboarding-quest.html','dist/onboarding-dag-gps.html']){const page=await browser.newPage({viewport:{width:1920,height:1080},reducedMotion:'reduce'});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});page.on('request',r=>{if(!/^(file|blob):/.test(r.url()))report.requests.push(r.url())});await page.goto(pathToFileURL(path.resolve(file)).href);for(const width of [1920,1280,390]){await page.setViewportSize({width,height:width===1920?1080:800});await page.waitForTimeout(250);const screen='artifacts/release-'+path.basename(path.dirname(file))+'-'+path.basename(file,'.html')+'-'+width+'.png';await page.screenshot({path:screen,fullPage:true});report.screenshots.push(path.resolve(screen));const state={file,width,overflow:await page.evaluate(()=>({document:document.documentElement.scrollWidth,viewport:innerWidth})),keyboard:[],reducedMotion:await page.evaluate(()=>({preference:matchMedia('(prefers-reduced-motion:reduce)').matches,animation:getComputedStyle(document.getElementById('dag')||document.body).animationDuration,transition:getComputedStyle(document.getElementById('dag')||document.body).transitionDuration}))};assert.equal(state.reducedMotion.preference,true);assert.equal(state.reducedMotion.animation,'0s');assert.equal(state.reducedMotion.transition,'0s');await page.keyboard.press('Tab');state.keyboard.push(await page.evaluate(()=>({tag:document.activeElement.tagName,id:document.activeElement.id,outline:getComputedStyle(document.activeElement).outlineStyle})));await page.keyboard.press('Escape');if(report.axe){await page.addScriptTag({path:axe});const result=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));state.axe={engineVersion:result.testEngine.version,violations:result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),passes:result.passes.length,incomplete:result.incomplete.map(v=>({id:v.id,nodes:v.nodes.length})),inapplicable:result.inapplicable.length};}report.states.push(state);}
if(file.includes('index.html')){
 await page.setViewportSize({width:1280,height:800});await page.waitForTimeout(250);
 const find=file.includes('quest')?'lib/runner-client.ts':'scripts/build_map.py';
 async function active(name){const state={file,width:1280,active:name,overflow:await page.evaluate(()=>({document:document.documentElement.scrollWidth,viewport:innerWidth}))};
  if(report.axe){const result=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));state.axe={engineVersion:result.testEngine.version,violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),passes:result.passes.length,incomplete:result.incomplete.map(v=>({id:v.id,nodes:v.nodes.length}))};}
  state.svgContrast=await page.evaluate(()=>{function lum(s){const nums=s.match(/[\d.]+/g).slice(0,3).map(Number).map(c=>{c/=255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4});return .2126*nums[0]+.7152*nums[1]+.0722*nums[2];}
   return [...document.querySelectorAll('#nodes .node text')].map(t=>{const node=t.closest('.node'),fg=getComputedStyle(t).fill,bg=getComputedStyle(node.querySelector('.box')).fill,a=lum(fg),b=lum(bg);return {id:node.dataset.id,text:t.textContent,foreground:fg,background:bg,opacity:getComputedStyle(node).opacity,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};});});
  assert.ok(state.svgContrast.every(t=>t.ratio>=4.5&&Number(t.opacity)===1),'Manual computed SVG text contrast');report.states.push(state);
 }
 await page.locator('#ask').fill('locate '+find);await page.locator('#ask').press('Enter');await active('exact-file answer/details');
 await page.locator('[data-impact]').click();await active('potential-impact');await page.locator('#impact-close').click();
 await page.locator('#alias-manager > summary').click();await active('alias-manager');
 await page.locator('#feedback-manager > summary').click();await active('feedback-consent');
 await page.locator('#trust-panel > summary').click();await active('trust-findings');
 if(file.includes('quest')){await page.locator('#tour-select').selectOption({index:1});await page.locator('[data-tour-evidence]').first().click();await active('tour-source-dialog');await page.keyboard.press('Escape');}
}
await page.close();}fs.writeFileSync('artifacts/release-accessibility.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.states.map(s=>({file:s.file,width:s.width,overflow:s.overflow,violations:s.axe?.violations.map(v=>v.id)}))));assert.deepEqual(report.errors,[]);assert.deepEqual(report.requests,[]);assert.ok(report.states.every(s=>s.overflow.document<=s.overflow.viewport));if(!process.argv.includes('--observe'))assert.ok(report.axe&&report.states.every(s=>s.axe.violations.length===0),'Axe violations or missing engine; inspect report');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
