#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{performance}=require('node:perf_hooks'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_DIR||'/Users/aibert/projects/quest-coder-assist/node_modules/playwright'),{synthetic,stats}=require('./bench_release.cjs');
(async()=>{const browser=await chromium.launch(),report={timestamp:new Date().toISOString(),browserVersion:browser.version(),playwrightVersion:require(path.join(process.env.PLAYWRIGHT_DIR||'/Users/aibert/projects/quest-coder-assist/node_modules/playwright','package.json')).version,method:'Raw shipped layout API over all file nodes/edges (5 samples); full Ask is DOM click dispatch through scorer, routing, layout and render plus two requestAnimationFrame paint opportunities (20 samples after 5 warmups). Excludes Playwright transport, input typing, browser compositor completion and filesystem IO. Cold page includes navigation and boot. Not scorer-only, not guaranteed paint-to-screen.',fixtures:[],errors:[],requests:[],screenshots:[]};try{for(const size of [1000,5000]){const map=synthetic(size),base='artifacts/release-synthetic-'+size;fs.writeFileSync(base+'.json',JSON.stringify(map));execFileSync('python3',['scripts/render.py','--map',base+'.json','--without-tours','--out','dist/release-synthetic-'+size+'.html']);}
for(const [name,file,mapFile] of [['quest','dist/quest-refresh/index.html','dist/quest-refresh/map.json'],['self-legacy','dist/dag-gps/index.html','dist/dag-gps/map.json'],['self-onboarding','dist/onboarding-dag-gps/index.html','dist/onboarding-dag-gps/map.json'],...[1000,5000].map(n=>['synthetic-'+n,'dist/release-synthetic-'+n+'.html','artifacts/release-synthetic-'+n+'.json'])]){const map=JSON.parse(fs.readFileSync(mapFile)),page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});page.on('request',r=>{if(!/^(file|blob):/.test(r.url()))report.requests.push(r.url())});const start=performance.now();await page.goto(pathToFileURL(path.resolve(file)).href);await page.waitForFunction(()=>window.dagGps);const cold=performance.now()-start;const fixture={name,nodes:map.nodes.length,files:map.nodes.filter(n=>n.kind==='file').length,cold_page_boot_ms:cold};fixture.layout=await page.evaluate(map=>{const samples=[],files=map.nodes.filter(n=>n.kind==='file');let count;for(let i=0;i<5;i++){const n=files.map(n=>({id:n.id,w:238,h:52,t1:n.label,t2:'file'})),e=map.file_edges.map(e=>({...e})),t=performance.now();const g=dagGps.layout(n,e);samples.push(performance.now()-t);count={nodes:g.nodes.length,edges:g.edges.length};}return {samples,count};},map);assert.equal(fixture.layout.count.nodes,fixture.files);assert.equal(fixture.layout.count.edges,map.file_edges.filter(e=>e.from!==e.to).length);
const files=map.nodes.filter(n=>n.kind==='file'),queries=[`locate ${files.at(-1).id}`,'quantum teleporter',`path from ${files[0].id} to ${files.at(-1).id}`];fixture.ask=[];for(const q of queries){const times=await page.evaluate(async query=>{const a=[],pipeline=[];for(let i=0;i<25;i++){document.getElementById('ask').value=query;const t=performance.now();document.getElementById('ask-submit').click();const synchronous=performance.now()-t;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));if(i>=5){a.push(performance.now()-t);pipeline.push(synchronous);}}return {paintOpportunities:a,synchronousPipeline:pipeline};},q);fixture.ask.push({query:q,full_ask_render:stats(times.synchronousPipeline),including_two_paint_opportunities:stats(times.paintOpportunities)});}
if(name.startsWith('synthetic')){await page.locator('#ask').fill('locate '+files.at(-1).id);await page.locator('#ask').press('Enter');assert.equal((await page.evaluate(()=>dagGps.state())).focused,files.at(-1).id);assert.equal(await page.locator('#nodes [data-id="'+files.at(-1).id+'"]').count(),1);await page.locator('#btn-back').click();await page.locator('#panel [data-go="synthetic"]').click();assert.ok(await page.locator('#panel [data-file]').count()<=150);await page.locator('#panel [data-row-page="1"]').click();assert.match(await page.locator('#panel').innerText(),/Showing 151/);await page.locator('[data-expand="synthetic"]').click();assert.match(await page.locator('#crumb').innerText(),/showing 80/);assert.ok((await page.evaluate(()=>dagGps.state())).visibleNodes<=80);await page.locator('#btn-file-next').click();assert.match(await page.locator('#crumb').innerText(),/page 2/);await page.locator('#btn-file-prev').click();const state=await page.evaluate(()=>dagGps.state());assert.equal(state.visibleNodes,80);assert.ok(state.visibleEdges>=2,'Cycle edges retained within first page');fixture.boundedView={fileGraphNodes:state.visibleNodes,totalFiles:files.length,fileRowLimit:150,cyclePreserved:true,lateFileAskVisible:true};await page.locator('#btn-readable').click();for(const width of [1280,390]){await page.setViewportSize({width,height:800});await page.waitForTimeout(250);await page.locator('#btn-readable').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const safe=await page.evaluate(()=>{const svg=document.getElementById('dag').getBoundingClientRect(),toolbar=document.querySelector('.toolbar').getBoundingClientRect(),legend=document.getElementById('legend').getBoundingClientRect();return {svg:svg.toJSON(),toolbar:toolbar.toJSON(),legend:legend.toJSON(),clipping:getComputedStyle(document.getElementById('dag')).overflow};});
assert.ok(safe.svg.top>=safe.toolbar.bottom&&safe.svg.bottom<=safe.legend.top,'Controls and legend outside graph viewport');assert.equal(safe.clipping,'hidden');
fixture.boundedView.controlsSeparated=true;const screenshot='artifacts/release-scale-'+name+'-'+width+'.png';await page.screenshot({path:screenshot});report.screenshots.push(path.resolve(screenshot));}}
report.fixtures.push(fixture);await page.close();}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.requests,[]);fs.writeFileSync('artifacts/release-ui-performance.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.fixtures.map(f=>({name:f.name,cold:f.cold_page_boot_ms,raw_layout:f.layout.samples,ask:f.ask,bounded:f.boundedView}))));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
