#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),{performance}=require('node:perf_hooks');
const S=require('../web/scorer.js');
function synthetic(size){const layer={id:'synthetic',kind:'layer',lines:size-1,label:'Synthetic fixtures',aliases:['fixture architecture'],desc:'Generated scale fixture',path:''};const files=Array.from({length:size-1},(_,i)=>({id:`src/file${i}.js`,kind:'file',path:`src/file${i}.js`,label:`file${i}.js`,layer:'synthetic',aliases:[]}));const links=files.slice(1).map((n,i)=>({from:n.id,to:files[Math.floor(i/4)].id,type:'import',cross_layer:false}));links.push({from:files[0].id,to:files[1].id,type:'import',cross_layer:false});return {meta:{repo:'synthetic/scale',ref:'GENERATED FIXTURE — no Git source',synthetic:true,commit:'f'.repeat(40),snapshot_commit:'f'.repeat(40),built_at:new Date().toISOString(),counts:{files:files.length,layers:1,edges:0,file_edges:links.length}},nodes:[layer,...files],edges:[],file_edges:links,layers:{synthetic:{files:files.map(n=>n.id),label:layer.label,upstream:[],downstream:[],top_fan_in:[]}}};}
function stats(a){a.sort((a,b)=>a-b);return {samples:a.length,p50_ms:a[Math.ceil(a.length*.5)-1],p95_ms:a[Math.ceil(a.length*.95)-1],max_ms:a.at(-1)};}
function bench(name,map,syntheticFixture,mapLoading){const t=performance.now(),scorer=S.createScorer(map);const init=performance.now()-t;const files=map.nodes.filter(n=>n.kind==='file');const queries=[`locate ${files[0].id}`,'quantum teleporter',`path from ${files[0].id} to ${files.at(-1).id}`,'dependencies of '+map.nodes.find(n=>n.kind==='layer').label];const modes=[];for(const overlay of [[],[{alias:'release fixture nickname',nodeId:files[0].id}]]){const sc=overlay.length?S.createScorer(map,overlay):scorer;const results=[];for(const query of [...queries,'release fixture nickname']){for(let i=0;i<50;i++)sc.score(query);const times=[];for(let i=0;i<1000;i++){const t=performance.now();sc.score(query);times.push(performance.now()-t);}const result=sc.score(query);results.push({query,operation:result.operation.choice,yes:result.yes,...stats(times)});}modes.push({aliasMode:overlay.length?'on':'off',queries:results});}return {name,synthetic:syntheticFixture,nodes:map.nodes.length,files:files.length,edges:(map.edges||[]).length+(map.file_edges||[]).length,cold_map_load:mapLoading,cold_scorer_init_ms:init,modes};}
if(require.main===module){const output=process.argv[2]||'artifacts/release-performance.json';const fixtures=[['quest','maps/quest-coder/map.json'],['self-legacy','dist/dag-gps/map.json'],['self-onboarding','dist/onboarding-dag-gps/map.json']].map(([n,p])=>{let t=performance.now();const text=fs.readFileSync(p,'utf8'),read=performance.now()-t;t=performance.now();const map=JSON.parse(text),parse=performance.now()-t;return [n,map,false,{file:p,bytes:Buffer.byteLength(text),read_ms:read,json_parse_ms:parse,osCache:'not flushed'}];});
for(const size of [1000,5000]){let t=performance.now();const generated=synthetic(size),generation=performance.now()-t,text=JSON.stringify(generated);t=performance.now();const map=JSON.parse(text),parse=performance.now()-t;fixtures.push(['synthetic-'+(size===1000?'1k':'5k'),map,true,{file:null,bytes:Buffer.byteLength(text),read_ms:null,generation_ms:generation,json_parse_ms:parse,osCache:'generated in memory; not file IO'}]);}const report={timestamp:new Date().toISOString(),environment:{platform:os.platform(),arch:os.arch(),cpus:os.cpus()[0].model,memory:os.totalmem(),loadAverage:os.loadavg(),logicalCpuCount:os.cpus().length,node:process.version,commit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim()},method:'50 warmups + 1000 samples per query/mode; inclusive scorer validation, exclusive UI/layout/routing; nearest-rank p95. Synthetic balanced graph includes a real file cycle; not a real repo.',fixtures:fixtures.map(([...a])=>bench(...a))};fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');const worst=Math.max(...report.fixtures.flatMap(f=>f.modes.flatMap(m=>m.queries.map(q=>q.p95_ms))));console.log(JSON.stringify({output,worst_p95_ms:worst,target_ms:10}));if(worst>=10&&!process.argv.includes('--observe'))process.exitCode=1;}
module.exports={synthetic,stats};
