#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_DIR||'/Users/aibert/projects/quest-coder-assist/node_modules/playwright');
const F=require('../web/query-feedback.js'),E=require('./eval_user_queries.cjs'),map=require('../maps/quest-coder/map.json');
const ROOT=path.resolve(__dirname,'..'),key='dag-gps:feedback:v1:'+encodeURIComponent(map.meta.repo),fixtures=['eval/eval.jsonl','eval/lookup.jsonl','eval/aliases.jsonl'].filter(f=>fs.existsSync(path.join(ROOT,f)));
const hashes=Object.fromEntries(fixtures.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex')]));
(async()=>{const browser=await chromium.launch();try{
 const c=await browser.newContext({viewport:{width:1920,height:1080},acceptDownloads:true}),page=await c.newPage(),errors=[],requests=[],checks=[],screenshots=[];
 function observe(p){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('request',r=>{if(!/^(file|blob):/.test(r.url()))requests.push(r.url());});}observe(page);
 const url=pathToFileURL(path.join(ROOT,'dist/quest-coder.html')).href;
 const saved=()=>page.evaluate(k=>localStorage.getItem(k),key),rows=async()=>JSON.parse(await saved()).records;
 async function ask(q){await page.locator('#ask').fill('');await page.locator('#ask').pressSequentially(q);await page.locator('#ask-submit').click();}
 async function open(){if(!await page.locator('#feedback-manager').evaluate(e=>e.open))await page.locator('#feedback-manager > summary').click();}
 async function shot(name){const f=path.join(ROOT,'artifacts/feedback-'+name+'.png');await page.screenshot({path:f});screenshots.push(f);}
 async function label(classification,expected,split='development'){const area=page.locator('.feedback-record').first();await area.locator('summary').first().click();await area.locator('[data-field="classification"]').selectOption(classification);if(expected){await area.locator('[data-field="operation"]').selectOption(expected.operation);for(const k of ['target','from','to'])await area.locator('[data-field="'+k+'"]').fill(expected[k]||'');if(expected.route)await area.locator('[data-field="route"]').selectOption(expected.route);}await area.locator('[data-field="split"]').selectOption(split);await area.locator('[data-feedback-save]').click();}
 async function upload(raw){await open();await page.locator('#feedback-import').setInputFiles({name:'feedback.json',mimeType:'application/json',buffer:Buffer.from(raw)});await page.waitForFunction(()=>document.getElementById('feedback-preview').textContent.length>0);}
 function check(name){checks.push(name);}
 await page.addInitScript(()=>{window.feedbackStorageCalls=[];for(const name of ['getItem','setItem']){const original=Storage.prototype[name];Storage.prototype[name]=function(k,...args){if(String(k).startsWith('dag-gps:feedback:'))window.feedbackStorageCalls.push(name);return original.call(this,k,...args);};}});await page.goto(url);await ask('Python judge');assert.deepEqual(await page.evaluate(()=>window.feedbackStorageCalls),[]);assert.equal(await saved(),null);assert.equal(await page.locator('#feedback-indicator').innerText(),'OFF');await open();assert.equal(await page.locator('#feedback-clear').isDisabled(),true);check('initial real typed Ask neither reads nor writes query history without consent');
 await open();await page.locator('#feedback-origin').selectOption('generated-fixture');await shot('consent-1920');await page.locator('#feedback-enable').click();assert.match(await page.locator('#feedback-indicator').innerText(),/RECORDING/);
 await ask('Python judge');assert.equal((await rows()).length,1);assert.equal((await rows())[0].origin,'generated-fixture');assert.equal((await rows())[0].expected,null);
 await label('Correct',{operation:'LOCATE',target:'runner-service'},'heldout');let r=(await rows())[0];assert.equal(r.split,'heldout');assert.ok(r.splitFrozenAt<=r.labeledAt);await page.locator('.feedback-record').first().locator('summary').first().click();assert.equal(await page.locator('.feedback-record').first().locator('[data-feedback-save]').count(),0);check('explicit fixture consent, compact captured answer, Correct expected target and immutable held-out label');
 await ask('where is bearer auth?');await label('Wrong',{operation:'LOCATE',target:'runner-service'});r=(await rows()).at(-1);assert.equal(r.answer.operation,'NOT_SURE');assert.equal(r.expected.target,'runner-service');assert.equal(await page.evaluate(()=>localStorage.getItem('dag-gps:aliases:v1:'+encodeURIComponent('erictweng/quest-coder'))),null);check('known synthetic bearer-auth abstention retained as Wrong confirmed intent; labels never add aliases');
 await ask('quantum teleporter');await label('Unclear',null);r=(await rows()).at(-1);assert.equal(r.expected,null);assert.equal(r.classification,'Unclear');check('Unclear has no gold operation and is not NOT_SURE truth');
 await ask('path from runner-service to persistence');const route=E.bfs(map,'runner-service','persistence')?'found':'none';await label('Correct',{operation:'PATH',from:'runner-service',to:'persistence',route});r=(await rows()).at(-1);assert.equal(r.expected.from,'runner-service');assert.equal(r.expected.to,'persistence');assert.equal(r.expected.route,route);check('PATH distinct expected endpoints and independently checked directed route truth');
 await ask('quantum flux');await label('Wrong',null);assert.equal((await rows()).at(-1).expected,null);await ask('where is runner.py?');assert.equal((await rows()).at(-1).classification,'unlabelled');assert.equal((await rows()).at(-1).expected,null);check('Wrong alone and runner.py query do not invent replacement/user intent');
 await ask('Python judge station');await page.locator('[data-override="runner-service"]').click();await page.locator('#alias-text').fill('Python judge station');await page.locator('#alias-review').click();await page.locator('#alias-confirm').click();await ask('Python judge station');await label('Correct',{operation:'LOCATE',target:'runner-service'});assert.deepEqual((await rows()).at(-1).overlay,[{alias:'Python judge station',nodeId:'runner-service'}]);check('separately confirmed alias captured as overlay provenance, not automatically taught by label');
 const count=(await rows()).length;await ask('impact of lib/runner-client.ts');assert.equal((await rows()).length,count);assert.match(await page.locator('#feedback-status').innerText(),/excluded/);await ask('walk me through Run basic');assert.equal((await rows()).length,count);check('impact and tour queries excluded visibly instead of forced scorer labels');
 await open();const promise=page.waitForEvent('download');await page.locator('#feedback-export').click();const dl=await promise,file=path.join(ROOT,'artifacts/feedback-export-generated.json');await dl.saveAs(file);const exported=fs.readFileSync(file,'utf8'),dataset=F.parse(exported,map.meta.repo);assert.ok(dataset.records.every(r=>r.origin==='generated-fixture'));assert.equal(dataset.records.length,count);
 execFileSync(process.execPath,['scripts/eval_user_queries.cjs','maps/quest-coder/map.json',file,'artifacts/feedback-export-eval.json'],{cwd:ROOT});const evaluation=JSON.parse(fs.readFileSync(path.join(ROOT,'artifacts/feedback-export-eval.json'),'utf8'));assert.equal(evaluation.ineligible.length,0);assert.equal(evaluation.eligible,4);assert.equal(evaluation.counts.Unclear,1);assert.equal(evaluation.userLabeledCases,0);assert.match(evaluation.message,/No labeled user cases yet/);assert.equal(evaluation.groups['generated-fixture/development']['alias-off'].unnecessaryAbstention.count,2);check('actual downloaded export evaluated by real CLI; fixture counts, original/alias modes, miss and absence of user accuracy honest');
 await page.reload();assert.equal(await page.locator('#feedback-indicator').innerText(),'OFF');await open();assert.equal(await page.locator('.feedback-record').count(),0);await page.locator('#feedback-origin').selectOption('generated-fixture');await page.locator('#feedback-enable').click();assert.equal(await page.locator('.feedback-record').count(),count);await page.locator('#feedback-disable').click();await ask('Python judge');assert.equal((await rows()).length,count);check('same-file persistence loaded only on fresh consent; reload and disable stop automatic capture');
 await open();page.once('dialog',d=>d.dismiss());await page.locator('#feedback-clear').click();assert.equal((await rows()).length,count);page.once('dialog',d=>d.accept());await page.locator('#feedback-clear').click();assert.equal((await rows()).length,0);
 await upload(exported);assert.equal((await rows()).length,0);await page.locator('#feedback-import-confirm').click();assert.match(await page.locator('#feedback-preview').innerText(),/consent/);await page.locator('#feedback-enable').click();await upload(exported);await shot('import-preview');await page.locator('#feedback-import-confirm').click();assert.equal((await rows()).length,count);check('clear cancellation/confirmation, import preview inert until recording consent plus replace confirmation');
 const before=await saved(),base=JSON.parse(exported);let unknown=structuredClone(base);unknown.records[0].expected.target='invented-node';for(const bad of ['{',' '.repeat(F.MAX_BYTES+1),JSON.stringify({...base,version:2}),JSON.stringify({...base,repo:'other/repo'}),JSON.stringify(unknown),JSON.stringify({...base,records:[base.records[0],base.records[0]]})]){await upload(bad);assert.match(await page.locator('#feedback-preview').innerText(),/Import rejected; nothing changed/);assert.equal(await saved(),before);assert.equal(await page.locator('#feedback-import-confirm').count(),0);}check('six malformed/version/oversize/repo/unknown ID/duplicate imports rejected atomically');
 let stale=structuredClone(base);stale.records[0].id+='-stale-import';stale.records[0].snapshot.commit='a'.repeat(40);stale.records[0].snapshot.source.snapshot_commit='a'.repeat(40);await upload(JSON.stringify(stale));assert.match(await page.locator('#feedback-preview').innerText(),/1 stale/);await page.locator('#feedback-import-confirm').click();await page.locator('.feedback-record').last().locator('summary').first().click();assert.match(await page.locator('.feedback-record').last().innerText(),/INELIGIBLE/);check('foreign snapshot retained visibly ineligible with no target remapping');
 const evil='<img src=x onerror="window.feedbackPwned=1">';let inert=structuredClone(base);inert.records[0].id+='-inert-import';inert.records[0].question=evil;await upload(JSON.stringify(inert));await page.locator('#feedback-import-confirm').click();assert.equal(await page.locator('#feedback-list img').count(),0);assert.equal(await page.evaluate(()=>window.feedbackPwned),undefined);assert.match(await page.locator('#feedback-list').innerText(),/img src/);check('malicious question rendered as inert escaped DOM, no external requests');
 await page.locator('.feedback-record').first().locator('summary').first().click();await page.locator('.feedback-record').first().locator('[data-feedback-remove]').click();assert.equal((await rows()).length,count-1);check('single record removal persists without changing aliases');
 await page.locator('#feedback-import').setInputFiles({name:'fixture.json',mimeType:'application/json',buffer:Buffer.from(exported)});await page.locator('#feedback-import-confirm').click();await shot('history-1920');await page.setViewportSize({width:1280,height:800});await page.waitForTimeout(250);const pathId=(await rows()).find(r=>r.expected?.operation==='PATH').id;const pathArea=page.locator('[data-record="'+pathId+'"]');await pathArea.locator('summary').first().click();await pathArea.scrollIntoViewIfNeeded();assert.equal(await pathArea.locator('[data-field="from"]').inputValue(),'runner-service');assert.equal(await pathArea.locator('[data-field="to"]').inputValue(),'persistence');assert.match(await page.locator('#feedback-live').innerText(),/Recording locally/i);await shot('path-label-1280');assert.equal(await page.locator('body').evaluate(e=>e.scrollWidth<=window.innerWidth),true);check('1920/1280 compact disclosure and independent PATH editor readable without document overflow');
 for(const failure of ['denied','quota']){const ctx=await browser.newContext({viewport:{width:1280,height:800}});await ctx.addInitScript(kind=>{if(kind==='denied')Object.defineProperty(window,'localStorage',{get(){throw Error('storage denied');}});else Storage.prototype.setItem=function(){throw Error('quota exceeded');};},failure);const pg=await ctx.newPage();observe(pg);await pg.goto(url);await pg.locator('#feedback-manager > summary').click();await pg.locator('#feedback-origin').selectOption('generated-fixture');await pg.locator('#feedback-enable').click();await pg.locator('#ask').fill('Python judge');await pg.locator('#ask').press('Enter');assert.match(await pg.locator('#feedback-status').innerText(),/Unsaved/);assert.equal((await pg.evaluate(()=>dagGps.state())).route.from,'runner-service');const f=path.join(ROOT,'artifacts/feedback-storage-'+failure+'.png');await pg.screenshot({path:f});screenshots.push(f);await ctx.close();check('storage '+failure+' unsaved visible; Ask still navigates');}
 for(const f of fixtures)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex'),hashes[f]);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 const report={synthetic:true,description:'All browser questions/labels generated for feature verification, never Eric-authored ground truth',checks,checkCount:checks.length,screenshots,pageErrors:errors,externalRequests:requests,fixturesUnchanged:hashes,exportFile:file,exportedRecords:dataset.records.length,evaluation:{eligible:evaluation.eligible,counts:evaluation.counts,message:evaluation.message,provenance:evaluation.provenance}};fs.writeFileSync(path.join(ROOT,'artifacts/feedback-browser.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
