/* Trusted shipped UI, evaluated inside template closure. */
(function(){
'use strict';
var F=DagGpsFeedback, storage;
try{storage=window.localStorage;}catch(e){storage={getItem:function(){throw e;},setItem:function(){throw e;}};}
var store=F.createStore(MAP,storage,FEEDBACK_PROVENANCE), pending=null, generation=0;
var host=document.createElement('details');host.id='feedback-manager';
host.innerHTML='<summary>Query feedback · <span id="feedback-indicator">OFF</span></summary><p>Explicit consent: stores questions, compact answers, corrections, full source snapshot metadata and the active alias overlay locally only. No networking/telemetry. Separate from learned aliases; labels never teach aliases. Tours and impact Ask are excluded: curated narratives/potential impact have no scorer operation label.</p><p>Retains newest 200 records, up to 90 days, ≤2 MiB persisted/exported. Expiry is applied on enable/write. file:// storage is best-effort; export before closing an unsaved session. Imports replace history only after preview and consent.</p><label>Data origin <select id="feedback-origin"><option value="user">My real user queries</option><option value="generated-fixture">Generated development fixture (not user accuracy)</option></select></label><button class="btn" id="feedback-enable" type="button">Enable local recording (I consent)</button> <button class="btn ghost" id="feedback-disable" type="button">Disable recording</button><p id="feedback-status" role="status"></p><button class="btn" id="feedback-export" type="button">Export JSON</button> <button class="btn ghost" id="feedback-clear" type="button">Clear all…</button><label>Import JSON (preview, then replace)<input id="feedback-import" type="file" accept="application/json,.json"></label><div id="feedback-preview"></div><div id="feedback-list"></div>';
document.querySelector('aside').prepend(host);
function el(id){return document.getElementById(id);}
function refresh(){var s=store.state();el('feedback-indicator').textContent=s.enabled?'● RECORDING locally':'OFF';el('feedback-indicator').style.color=s.enabled?'var(--accent)':'';el('feedback-live').textContent=s.enabled?'● Recording locally':'local / offline';el('feedback-live').style.color=s.enabled?'var(--accent)':'';el('feedback-live').style.display=s.enabled?'inline':'';el('feedback-status').textContent=s.status;el('feedback-enable').disabled=s.enabled;el('feedback-disable').disabled=!s.enabled;el('feedback-origin').disabled=s.enabled;el('feedback-clear').disabled=!s.consented;el('feedback-clear').title=s.consented?'Clear loaded history':'Enable local access consent before managing existing history';
 el('feedback-list').innerHTML=s.records.slice().reverse().map(function(r){var reason=F.eligibility(r,MAP,FEEDBACK_PROVENANCE);var frozen=r.split==='heldout'||!!reason;
 return '<details class="feedback-record" data-record="'+esc(r.id)+'"><summary>'+esc(r.classification)+' · '+esc(r.question)+' · '+esc(r.split)+'</summary><p>'+esc(r.origin)+' · '+esc(r.snapshot.commit)+' · original '+esc(r.answer.operation)+' · '+esc(r.answer.reason)+'</p><details><summary>Original answer / alias provenance</summary><pre>'+esc(JSON.stringify({answer:r.answer,overlay:r.overlay,mapSha256:r.snapshot.mapSha256,scorerSha256:r.snapshot.scorerSha256},null,2))+'</pre></details>'+ (reason?'<p>INELIGIBLE: '+esc(reason)+'</p>':'')+'<details><summary>Label / split safeguards</summary><p>Label is your judgment; a Wrong answer does not imply any replacement. Unclear is never NOT_SURE truth. Correct is only prefilled for review, not saved automatically. Select split before confirming truth. Held-out is permanently frozen before tuning; development split is also immutable.</p></details>'+(!frozen?'<label>Classification <select data-field="classification"><option value=""'+(r.classification==='unlabelled'?' selected':'')+'>Choose a label</option><option'+(r.classification==='Correct'?' selected':'')+'>Correct</option><option'+(r.classification==='Wrong'?' selected':'')+'>Wrong</option><option'+(r.classification==='Unclear'?' selected':'')+'>Unclear</option></select></label><label>Expected operation (optional until confirmed)<select data-field="operation"><option value="">Not yet known</option>'+F.OPERATIONS.map(function(op){return '<option'+(r.expected?.operation===op?' selected':'')+'>'+op+'</option>';}).join('')+'</select></label><label>Expected target ID <input data-field="target" value="'+esc(r.expected?.target||'')+'" maxlength="500" list="feedback-node-ids"></label><label>PATH from ID <input data-field="from" value="'+esc(r.expected?.from||'')+'" maxlength="500" list="feedback-node-ids"></label><label>PATH to ID <input data-field="to" value="'+esc(r.expected?.to||'')+'" maxlength="500" list="feedback-node-ids"></label><label>PATH directed truth <select data-field="route"><option value="">Not labeled</option><option value="found"'+(r.expected?.route==='found'?' selected':'')+'>Route exists</option><option value="none"'+(r.expected?.route==='none'?' selected':'')+'>No route</option></select></label><label>Designate split before confirming truth <select data-field="split"'+(r.split!=='unassigned'?' disabled':'')+'><option value="unassigned">Unassigned (not held-out)</option><option value="development"'+(r.split==='development'?' selected':'')+'>Development</option><option value="heldout">Held-out — freezes label permanently</option></select></label><button class="btn" data-feedback-save type="button">Confirm label / expectations</button>':'<p>Frozen/ineligible: no label edits. Export preserves original provenance; no remapping.</p>')+' <button class="btn ghost" data-feedback-remove type="button">Remove record</button><p data-feedback-message role="status"></p></details>';
 }).join('')||'<p>No query records. No labeled user cases yet.</p>';
}
var ids=document.createElement('datalist');ids.id='feedback-node-ids';ids.innerHTML=MAP.nodes.map(function(n){return '<option value="'+esc(n.id)+'">'+esc(n.label||n.id)+'</option>';}).join('');host.append(ids);
el('feedback-enable').onclick=function(){store.enable(el('feedback-origin').value);refresh();};
el('feedback-disable').onclick=function(){store.disable();refresh();};
el('feedback-clear').onclick=function(){if(confirm('Clear ALL local query history? This does not change learned aliases.')){store.clear();refresh();}};
el('feedback-export').onclick=function(){var url=URL.createObjectURL(new Blob([store.serialize()],{type:'application/json'}));var a=document.createElement('a');a.href=url;a.download='dag-gps-query-feedback-v1.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);};
el('feedback-list').addEventListener('change',function(ev){if(ev.target.getAttribute('data-field')!=='classification')return;var area=ev.target.closest('[data-record]');var r=store.state().records.find(function(x){return x.id===area.dataset.record;});var val=ev.target.value;function set(k,v){area.querySelector('[data-field="'+k+'"]').value=v||'';}
 ['operation','target','from','to','route'].forEach(function(k){set(k,'');});if(val==='Correct'&&r.answer.yes){set('operation',r.answer.operation);set('target',r.answer.targets.locate_target?.choice);set('from',r.answer.targets.from_target?.choice);set('to',r.answer.targets.to_target?.choice);} });
el('feedback-list').onclick=function(ev){var area=ev.target.closest('[data-record]');if(!area)return;var id=area.dataset.record;if(ev.target.closest('[data-feedback-remove]')){store.remove(id);refresh();return;}if(!ev.target.closest('[data-feedback-save]'))return;
 try{function value(k){return area.querySelector('[data-field="'+k+'"]').value;}var classification=value('classification'),op=value('operation'),expected=null;
 if(classification!=='Unclear'&&op){expected={operation:op,target:['LOCATE','UPSTREAM','DOWNSTREAM'].includes(op)?value('target'):null,from:op==='PATH'?value('from'):null,to:op==='PATH'?value('to'):null,route:op==='PATH'?(value('route')||null):null};}
 store.label(id,classification,expected,value('split'));refresh();}catch(e){area.querySelector('[data-feedback-message]').textContent='Label not saved: '+e.message;}
};
el('feedback-import').onchange=async function(ev){var token=++generation;pending=null;el('feedback-preview').textContent='';var file=ev.target.files[0];if(!file)return;try{if(file.size>F.MAX_BYTES)throw Error('Feedback file exceeds 2 MiB');var raw=await file.text();if(token!==generation)return;pending=store.preview(raw);el('feedback-preview').innerHTML='<p>Replace with '+pending.dataset.records.length+' records; '+pending.ineligible+' stale/different snapshot records kept INELIGIBLE, no rebinding. Import never enables recording or learns aliases. Questions may contain private source information.</p><button class="btn" id="feedback-import-confirm" type="button">I consent: replace local history</button><button class="btn ghost" id="feedback-import-cancel" type="button">Cancel</button>';}catch(e){el('feedback-preview').textContent='Import rejected; nothing changed: '+e.message;}ev.target.value='';};
el('feedback-preview').onclick=function(ev){if(ev.target.id==='feedback-import-cancel'){pending=null;el('feedback-preview').textContent='Import cancelled.';}else if(ev.target.id==='feedback-import-confirm'&&pending){try{store.commit(pending);pending=null;refresh();el('feedback-preview').textContent='Import applied. '+store.state().status;}catch(e){el('feedback-preview').textContent='Import rejected; nothing changed: '+e.message;}}};
refresh();
return {capture:function(question,result){try{store.capture(question,result,aliasStore.overlay(),el('feedback-origin').value);refresh();}catch(e){el('feedback-status').textContent='Not recorded; Ask unaffected: '+e.message;}},excluded:function(){if(store.state().enabled)el('feedback-status').textContent='Not recorded: tour/impact Ask excluded (no compatible scorer operation schema).';}};
})();
